#!/bin/bash

curDir=`pwd`;

scriptDir=${0%/*};
cd $scriptDir;
scriptDir=`pwd`;
cd $curDir

sudo echo "";

echo "Y" | sudo apt-get update;
echo "Y" | sudo apt-get upgrade;

mkdir ~/bin

grep 'export PATH="${PATH}:~/bin"' ~/.bashrc >> /dev/null
if [ $? != 0 ]
then
	echo 'export PATH="${PATH}:~/bin"' | sudo tee -a ~/.bashrc >> /dev/null
fi


mkdir -p ~/Programs

echo "Y" | sudo apt-get remove pitivi #del pitivi for change video
echo "Y" | sudo apt-get remove empathy empathy-common nautilus-sendto-empathy #The client of instant messages
echo "Y" | sudo apt-get remove gwibber gwibber-service #The client of microblogs
echo "Y" | sudo apt-get remove vino #for show destop.
echo "Y" | sudo apt-get remove computer-janitor-gtk # for system clearing.
echo "Y" | sudo apt-get remove rhythmbox totem totem-common #default video and audio players.
echo "Y" | sudo apt-get remove banshee # banshee.
echo "Y" | sudo dpkg -r transmission-common transmission-gtk # remode default bit-torrent client.
echo "Y" | sudo apt-get install --allow-unauthenticated kate wine
echo "Y" | sudo apt-get install --allow-unauthenticated libmono-winforms2.0-cil # install winform for mono

# browsers
echo "Y" | sudo apt-get install --allow-unauthenticated chromium-browser 

echo "Y" | sudo add-apt-repository "deb http://deb.opera.com/opera/ stable non-free"
wget -O - http://deb.opera.com/archive.key | sudo apt-key add -
echo "Y" | sudo apt-get update
echo "Y" | sudo apt-get install --allow-unauthenticated opera
# /browsers

echo "Archivers and curl"
echo "Y" | sudo apt-get install --allow-unauthenticated alien dpkg-dev debhelper build-essential p7zip p7zip-full unace arj 
echo "Y" | sudo apt-get install --allow-unauthenticated lha cpio curl zip rar unrar

echo "goldendict pidgin git"
echo "Y" | sudo apt-get install --allow-unauthenticated goldendict pidgin

echo "install deadbeef - audio player."
echo "Y" | sudo add-apt-repository ppa:alexey-smirnov/deadbeef
echo "Y" | sudo apt-get update
echo "Y" | sudo apt-get install --allow-unauthenticated deadbeef

echo "Y" | sudo apt-get install --allow-unauthenticated ubuntu-restricted-extras # Codecs
echo "Y" | sudo apt-get install --allow-unauthenticated vlc mozilla-plugin-vlc # video player.

echo "Y" | sudo apt-get install --allow-unauthenticated ktorrent

echo "Y" | sudo apt-get install --allow-unauthenticated krusader

# install java 5
echo "Y" | sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ hardy main multiverse"
echo "Y" | sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ hardy-updates main multiverse"
echo "Y" | sudo apt-get update
#echo "Y" | apt-get install sun-java5-jdk
# /install java 5


echo "Y" | sudo apt-get install --allow-unauthenticated openjdk-6-jdk
echo "Y" | sudo apt-get install --allow-unauthenticated git-core gnupg flex bison gperf libsdl-dev libesd0-dev 
echo "Y" | sudo apt-get install --allow-unauthenticated libwxgtk2.6-dev build-essential libncurses5-dev zlib1g-dev ia32-libs
echo "Y" | sudo apt-get install --allow-unauthenticated lib32z1-dev lib32ncurses5-dev gcc-multilib g++-multilib pngcrush 
echo "Y" | sudo apt-get install --allow-unauthenticated squashfs-tools squashfs-tools-dbg wget schedtool libc6-dev 
echo "Y" | sudo apt-get install --allow-unauthenticated x11proto-core-dev libx11-dev lib32readline5-dev lib32z-dev 
echo "Y" | sudo apt-get install --allow-unauthenticated libgl1-mesa-dev mingw32 gcc-4.3-multilib g++-4.3-multilib
echo "Y" | sudo apt-get install --allow-unauthenticated xserver-xorg-input-evtouch dpkg-dev
echo "Y" | sudo apt-get install --allow-unauthenticated libnss3-tools rpl
echo "Y" | sudo apt-get install --allow-unauthenticated bouml; # install bouml

echo "Installing skype"
echo "Y" | sudo add-apt-repository "deb http://archive.canonical.com/ubuntu maverick partner"
echo "Y" | sudo apt-get update
echo "Y" | sudo apt-get install --allow-unauthenticated skype

# install crebs for create wallpapers slideshow
add-apt-repository ppa:crebs/ppa
echo "Y" | apt-get update
echo "Y" | apt-get install --allow-unauthenticated crebs
# /install crebs for create wallpapers slideshow

# install VirtualBox
grep 'deb http://download.virtualbox.org/virtualbox/debian' ~/.bashrc >> /dev/null
if [ $? != 0 ]
then
	echo "Y" | sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian maverick contrib non-free"
	wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
fi
echo 'Y' | sudo apt-get update
echo 'Y' | sudo apt-get install --allow-unauthenticated virtualbox-4.1

cd $curDir;
# /install VirtualBox


# install unyaffs2
rm -rf ~/Programs/yaffs2utils;
mkdir -p ~/Programs/yaffs2utils;
cd ~/Programs/yaffs2utils;

wget http://yaffs2utils.googlecode.com/files/yaffs2utils.tar.gz;
tar -zxvf yaffs2utils.tar.gz yaffs2utils;
cd yaffs2utils/src;
make;
mv unyaffs2 ~/bin
mv mkyaffs2 ~/bin
mv unspare2 ~/bin

cd $curDir
# /install unyaffs2

#gconftool-2 --set "/apps/metacity/general/button_layout" --type string "menu:minimize,maximize,close" # close to the right

echo 'SUBSYSTEM=="usb", SYSFS{idVendor}=="0bb4", MODE="0666"' | sudo tee /etc/udev/rules.d/51-android.rules >> /dev/null # for htc
sudo chmod a+r /etc/udev/rules.d/51-android.rules

# download repo
curl https://android.git.kernel.org/repo > ~/bin/repo
chmod a+x ~/bin/repo
# /download repo

#install FUSON-exFAT
#-----------------
sudo add-apt-repository ppa:relan/exfat
echo "Y" | sudo apt-get update
echo "Y" | sudo apt-get install --allow-unauthenticated fuse-exfat
#-----------------

# install split_bootimg
rm -rf ~/Programs/Split_bootimg;
mkdir ~/Programs/Split_bootimg;
cd ~/Programs/Split_bootimg;

wget http://zen-droid.googlecode.com/files/split_bootimg.pl
chmod +x split_bootimg.pl
cp split_bootimg.pl ~/bin/split_bootimg.pl

cd $curDir
# /install split_bootimg

# download sdk
mkdir -p ~/Programs/Android

rm -rf ~/Programs/Android/SDK;
mkdir ~/Programs/Android/SDK;
cd ~/Programs/Android/SDK;

wget http://dl.google.com/android/android-sdk_r16-linux.tgz
tar -xf android-sdk_r16-linux.tgz

mkdir -p ~/Applications
mv -f android-sdk-linux/ ~/Applications/SDK

grep 'export PATH="${PATH}:~/Applications/SDK/tools"' ~/.bashrc >> /dev/null
if [ $? != 0 ]
then
	echo 'export PATH="${PATH}:~/Applications/SDK/tools"' | sudo tee -a ~/.bashrc >> /dev/null
fi

grep 'export PATH="${PATH}:~/Applications/SDK/platform-tools"' ~/.bashrc >> /dev/null
if [ $? != 0 ]
then
	echo 'export PATH="${PATH}:~/Applications/SDK/platform-tools"' | sudo tee -a ~/.bashrc >> /dev/null
fi

~/Applications/SDK/tools/android &
# /download sdk

# Download NDK
mkdir -p ~/Programs/Android

rm -rf ~/Programs/Android/NDK;
mkdir ~/Programs/Android/NDK;
cd ~/Programs/Android/NDK;

wget http://dl.google.com/android/ndk/android-ndk-r7b-linux-x86.tar.bz2
tar -jxvf android-ndk-r7b-linux-x86.tar.bz2

mkdir -p ~/Applications
mv -f android-ndk-r7b/ ~/Applications/NDK

grep 'export PATH="${PATH}:~/Applications/NDK"' ~/.bashrc >> /dev/null
if [ $? != 0 ]
then
	echo 'export PATH="${PATH}:~/Applications/NDK"' | sudo tee -a ~/.bashrc >> /dev/null
fi
# /Download NDK

# download eclipse
rm -rf ~/Programs/JAVA/Eclipse
mkdir -p ~/Programs/JAVA/Eclipse
cd ~/Programs/JAVA/Eclipse

mkdir -p ~/Applications

curl http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/eclipse/downloads/drops/R-3.7-201106131736/eclipse-SDK-3.7-linux-gtk-x86_64.tar.gz > eclipse.tar.gz
gzip -dc eclipse.tar.gz | tar -x
mv eclipse ~/Applications/EclipseAndroid

ln -s ~/Applications/EclipseAndroid/eclipse ~/Desktop/eclipseAndroid
~/Applications/EclipseAndroid/eclipse &

echo '==============================='
echo '==============================='
echo '==============================='
echo 'Android Development Tools - https://dl-ssl.google.com/android/eclipse/';
echo 'Android Development Tools - https://dl-ssl.google.com/android/eclipse/';
echo 'Android Development Tools - https://dl-ssl.google.com/android/eclipse/';
echo '==============================='
echo '==============================='
echo '==============================='

cd $curDir;
# /download eclipse

# install AgroUML
#mkdir -p ~/Programs/UML/AgroUML;
#cd ~/Programs/UML/AgroUML;
#curl  http://argouml-downloads.tigris.org/jws/argouml-latest-stable.jnlp > argouml-latest-stable.jnlp;
# /install AgroUML

cd $curDir;
exit 0;
